services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:latest
    container_name: forgejo
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Asia/Seoul
    ports:
      - "${PORT:-3000}:3000"
      - "222:22"
    volumes:
      - forgejo-data:/data

volumes:
  forgejo-data:
