run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: false

issues:
  new-from-rev: main
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
