version: 2

builds:
  - id: sfpanel
    main: ./cmd/sfpanel
    binary: sfpanel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: sfpanel
    formats:
      - tar.gz
    name_template: "sfpanel_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - configs/config.example.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: svrforum
    name: SFPanel
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto
