services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - kavita-config:/kavita/config
      - kavita-library:/library

volumes:
  kavita-config:
  kavita-library:
