services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - GLANCES_OPT=-w
    ports:
      - "${PORT:-61208}:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
