package release

import "testing"

func TestCompareVersions(t *testing.T) {
	tests := []struct {
		a, b string
		want int
	}{
		{"1.0.0", "1.0.0", 0},
		{"1.0.0", "1.0.1", -1},
		{"1.0.1", "1.0.0", 1},
		{"1.1.0", "1.0.99", 1},
		{"2.0.0", "1.99.99", 1},
		{"0.11.1", "0.11.10", -1},
		{"0.11.10", "0.11.2", 1},
		// Tolerate optional "v" prefix on either side.
		{"v1.2.3", "1.2.3", 0},
		{"1.2.3", "v1.2.3", 0},
		// Pre-release / build-metadata suffixes from `git describe`.
		// Treated as the base version for comparison purposes.
		{"v0.11.1-19-g2a7258c", "0.11.1", 0},
		{"0.11.1+build.42", "0.11.1", 0},
		{"v0.11.1-rc.1", "v0.11.2", -1},
	}
	for _, tt := range tests {
		got, err := CompareVersions(tt.a, tt.b)
		if err != nil {
			t.Fatalf("CompareVersions(%q, %q) unexpected error: %v", tt.a, tt.b, err)
		}
		if got != tt.want {
			t.Errorf("CompareVersions(%q, %q) = %d, want %d", tt.a, tt.b, got, tt.want)
		}
	}
}

func TestCompareVersionsInvalid(t *testing.T) {
	cases := []struct{ a, b string }{
		{"", "1.0.0"},
		{"1.0.0", ""},
		{"1.0", "1.0.0"},      // wrong segment count
		{"1.0.0.0", "1.0.0"},  // wrong segment count
		{"1.0.x", "1.0.0"},    // non-numeric
		{"1.0.0", "abc.d.ef"}, // non-numeric
	}
	for _, c := range cases {
		if _, err := CompareVersions(c.a, c.b); err == nil {
			t.Errorf("CompareVersions(%q, %q) expected error, got nil", c.a, c.b)
		}
	}
}

// ParseExpectedSHA256 is in the update verification path — a wrong return
// here is a silent bypass of the SHA-256 gate. Tested here rather than its
// own file because release/version_test.go already establishes the package
// test layout.

func TestParseExpectedSHA256_GoreleaserFormat(t *testing.T) {
	checksums := []byte(`a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890123456789012  sfpanel_0.11.2_linux_amd64.tar.gz
0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef  sfpanel_0.11.2_linux_arm64.tar.gz
`)
	got, err := ParseExpectedSHA256(checksums, "sfpanel_0.11.2_linux_amd64.tar.gz")
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got != "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890123456789012" {
		t.Errorf("got %q", got)
	}
}

func TestParseExpectedSHA256_GnuStarFormat(t *testing.T) {
	// `sha256sum -b` emits `<hash> *<filename>` for binary mode.
	checksums := []byte(`a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890123456789012 *sfpanel_0.11.2_linux_amd64.tar.gz
`)
	got, err := ParseExpectedSHA256(checksums, "sfpanel_0.11.2_linux_amd64.tar.gz")
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got != "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890123456789012" {
		t.Errorf("got %q", got)
	}
}

func TestParseExpectedSHA256_NotFound(t *testing.T) {
	checksums := []byte(`abc  some_other_file.tar.gz
`)
	_, err := ParseExpectedSHA256(checksums, "sfpanel_0.11.2_linux_amd64.tar.gz")
	if err == nil {
		t.Error("expected error when archive not in checksums file")
	}
}

func TestParseExpectedSHA256_LowercaseNormalisation(t *testing.T) {
	// goreleaser already emits lowercase, but a checksums file authored by
	// hand could be uppercase — the parser lowercases to match
	// hex.EncodeToString(sha256.Sum256(...)) which is always lowercase.
	checksums := []byte(`A1B2C3D4E5F60718293A4B5C6D7E8F9012345678901234567890123456789012  sfpanel_0.11.2_linux_amd64.tar.gz
`)
	got, err := ParseExpectedSHA256(checksums, "sfpanel_0.11.2_linux_amd64.tar.gz")
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got != "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890123456789012" {
		t.Errorf("got %q (want lowercase)", got)
	}
}

func TestParseExpectedSHA256_BlankAndCommentLinesSkipped(t *testing.T) {
	checksums := []byte(`# generated by sigstore-pipeline
abc  empty.tar.gz

a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890123456789012  sfpanel_0.11.2_linux_amd64.tar.gz
`)
	got, err := ParseExpectedSHA256(checksums, "sfpanel_0.11.2_linux_amd64.tar.gz")
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got != "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890123456789012" {
		t.Errorf("got %q", got)
	}
}

func TestIsForwardUpdate(t *testing.T) {
	if ok, _ := IsForwardUpdate("0.11.1", "0.11.2"); !ok {
		t.Error("0.11.1 -> 0.11.2 should be forward")
	}
	if ok, _ := IsForwardUpdate("0.11.2", "0.11.1"); ok {
		t.Error("0.11.2 -> 0.11.1 should NOT be forward (downgrade)")
	}
	if ok, _ := IsForwardUpdate("0.11.1", "0.11.1"); ok {
		t.Error("0.11.1 -> 0.11.1 should NOT be forward (equal)")
	}
	if _, err := IsForwardUpdate("1.0", "1.0.0"); err == nil {
		t.Error("invalid current version should error")
	}
}
