services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "${PORT:-13378}:80"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
      - audiobookshelf-audiobooks:/audiobooks
      - audiobookshelf-podcasts:/podcasts

volumes:
  audiobookshelf-config:
  audiobookshelf-metadata:
  audiobookshelf-audiobooks:
  audiobookshelf-podcasts:
