package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"strconv"

	"gopkg.in/yaml.v3"
)

type Config struct {
	Server   ServerConfig   `yaml:"server"`
	Database DatabaseConfig `yaml:"database"`
	Auth     AuthConfig     `yaml:"auth"`
	Docker   DockerConfig   `yaml:"docker"`
	Log      LogConfig      `yaml:"log"`
	Cluster  ClusterConfig  `yaml:"cluster"`
}

type ServerConfig struct {
	Host       string `yaml:"host"`
	Port       int    `yaml:"port"`
	StacksPath string `yaml:"stacks_path"` // Docker Compose project root scanned at startup
	// AllowedOrigins is merged into the CORS config. Defaults (dev server,
	// Tauri) are always honoured; additional values here let reverse-proxy
	// deployments (`https://panel.example.com`) work without a code change.
	AllowedOrigins []string `yaml:"allowed_origins"`
	// TrustedProxies is the allowlist of upstream addresses (or CIDR ranges)
	// permitted to set X-Forwarded-For / X-Real-IP. Without this, any client
	// can spoof their source IP, defeating the per-IP login rate limiter.
	// Defaults to ["127.0.0.0/8", "::1/128"] when empty so a same-host
	// reverse proxy keeps working out of the box.
	TrustedProxies []string `yaml:"trusted_proxies"`
}

type DatabaseConfig struct {
	Path string `yaml:"path"`
}

type AuthConfig struct {
	JWTSecret   string `yaml:"jwt_secret"`
	TokenExpiry string `yaml:"token_expiry"`
}

type DockerConfig struct {
	Socket        string              `yaml:"socket"`
	Observability ObservabilityConfig `yaml:"observability"`
}

// ObservabilityConfig controls the per-container metrics + events feature
// (theme F). Disabled means the collector / events listener / pruners do
// not start; new endpoints return empty arrays + observability_disabled flag.
//
// Enabled is a pointer so we can distinguish three states in YAML:
//   - field absent (nil)        → default-on (IsEnabled() = true)
//   - explicit `enabled: false` → off
//   - explicit `enabled: true`  → on
//
// A plain bool would collapse "absent" and "false" to the same zero value,
// which would silently re-enable observability for an operator who set
// `enabled: false` without also overriding the retention strings.
type ObservabilityConfig struct {
	Enabled          *bool  `yaml:"enabled"`
	MetricsRetention string `yaml:"metrics_retention"` // "6h" | "24h" | "72h"
	EventsRetention  string `yaml:"events_retention"`  // "7d" | "30d" | "90d"
}

// IsEnabled returns true when the operator hasn't explicitly disabled
// observability. Default-on: nil (block absent) → true. Explicitly false → false.
func (o ObservabilityConfig) IsEnabled() bool {
	return o.Enabled == nil || *o.Enabled
}

var (
	allowedMetricsRetentions = map[string]bool{"6h": true, "24h": true, "72h": true}
	allowedEventsRetentions  = map[string]bool{"7d": true, "30d": true, "90d": true}
)

type LogConfig struct {
	Level string `yaml:"level"`
	File  string `yaml:"file"`
}

type ClusterConfig struct {
	Enabled          bool   `yaml:"enabled"`
	Name             string `yaml:"name"`
	NodeID           string `yaml:"node_id"`
	NodeName         string `yaml:"node_name"`
	GRPCPort         int    `yaml:"grpc_port"`
	APIPort          int    `yaml:"-"` // Set from Server.Port at runtime, not persisted
	DataDir          string `yaml:"data_dir"`
	CertDir          string `yaml:"cert_dir"`
	AdvertiseAddress string `yaml:"advertise_address"`
	RaftTLS          bool   `yaml:"raft_tls"` // TLS encryption for Raft transport (set on init)
}

func (c *Config) Validate() error {
	if c.Server.Port <= 0 {
		return fmt.Errorf("server.port must be positive, got %d", c.Server.Port)
	}
	if c.Database.Path == "" {
		return fmt.Errorf("database.path is required")
	}
	// JWT secret can be auto-generated by Load(), but an env-var override like
	// SFPANEL_JWT_SECRET="" would leave it empty and let golang-jwt sign with
	// an empty key, which is trivially forgeable. 32 bytes (256-bit) is the
	// HS256 specification minimum for full security; 16 was a relic from an
	// earlier draft. Auto-generated secrets are 64 hex chars so this only
	// trips on manually-set short secrets.
	if len(c.Auth.JWTSecret) < 32 {
		return fmt.Errorf("auth.jwt_secret must be at least 32 characters (HS256 256-bit minimum)")
	}
	// Validate retention values whenever they're set, regardless of IsEnabled.
	// A typo like `metrics_retention: garbge` should fail at config-write time,
	// not silently lurk until the operator flips enabled and restarts. The
	// empty-string allowance is fine because Load() always fills defaults
	// before Validate() runs; it only matters for tests that build Config{}
	// by hand without going through Load().
	if r := c.Docker.Observability.MetricsRetention; r != "" && !allowedMetricsRetentions[r] {
		return fmt.Errorf("docker.observability.metrics_retention must be one of 6h/24h/72h, got %q", r)
	}
	if r := c.Docker.Observability.EventsRetention; r != "" && !allowedEventsRetentions[r] {
		return fmt.Errorf("docker.observability.events_retention must be one of 7d/30d/90d, got %q", r)
	}
	return nil
}

func (c *Config) ApplyEnvOverrides() {
	if v := os.Getenv("SFPANEL_PORT"); v != "" {
		if port, err := strconv.Atoi(v); err == nil {
			c.Server.Port = port
		}
	}
	if v := os.Getenv("SFPANEL_JWT_SECRET"); v != "" {
		c.Auth.JWTSecret = v
	}
	if v := os.Getenv("SFPANEL_DB_PATH"); v != "" {
		c.Database.Path = v
	}
	if v := os.Getenv("SFPANEL_LOG_LEVEL"); v != "" {
		c.Log.Level = v
	}
}

func Load(path string) (*Config, error) {
	cfg := &Config{
		Server:   ServerConfig{Host: "0.0.0.0", Port: 3628, StacksPath: "/opt/stacks"},
		Database: DatabaseConfig{Path: "./sfpanel.db"},
		Auth:     AuthConfig{TokenExpiry: "24h"},
		Docker:   DockerConfig{Socket: "unix:///var/run/docker.sock"},
		Log:      LogConfig{Level: "info"},
		Cluster: ClusterConfig{
			// Raft transport binds to GRPCPort+1 (manager.go:122), so the
			// default trio is 3628 HTTP / 3629 gRPC / 3630 Raft. Picked to
			// avoid the common 9xxx range that JupyterHub, Plausible,
			// Postgres-bouncer, et al. claim on a typical homeserver.
			GRPCPort: 3629,
			DataDir:  "/var/lib/sfpanel/cluster",
			CertDir:  "/etc/sfpanel/cluster",
		},
	}
	needsSave := false
	data, err := os.ReadFile(path)
	if err != nil {
		cfg.Auth.JWTSecret = generateRandomSecret()
		slog.Warn("no config file found, using defaults with random JWT secret")
		needsSave = true
	} else {
		if err := yaml.Unmarshal(data, cfg); err != nil {
			return nil, err
		}
	}
	if cfg.Auth.JWTSecret == "" {
		cfg.Auth.JWTSecret = generateRandomSecret()
		slog.Info("generated random JWT secret")
		needsSave = true
	}
	if cfg.Server.StacksPath == "" {
		cfg.Server.StacksPath = "/opt/stacks"
	}
	// docker.observability is default-on. Enabled is *bool so a missing block
	// (nil) means "use default-on" via IsEnabled(); only an explicit
	// `enabled: false` disables it. Fill missing retention strings here so
	// downstream code (and Validate's empty-string allowance) sees real values.
	if cfg.Docker.Observability.MetricsRetention == "" {
		cfg.Docker.Observability.MetricsRetention = "24h"
	}
	if cfg.Docker.Observability.EventsRetention == "" {
		cfg.Docker.Observability.EventsRetention = "30d"
	}
	cfg.ApplyEnvOverrides()
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("config validation: %w", err)
	}

	// Persist generated secrets so tokens survive restarts
	if needsSave {
		if saveData, err := yaml.Marshal(cfg); err == nil {
			if writeErr := AtomicWriteFile(path, saveData, 0600); writeErr != nil {
				slog.Warn("failed to persist generated config", "path", path, "error", writeErr)
			} else {
				slog.Info("config persisted with generated secrets", "path", path)
			}
		}
	}

	return cfg, nil
}

// AtomicWriteFile writes data to a temp file then renames to target path.
// This prevents partial writes from corrupting the config.
func AtomicWriteFile(path string, data []byte, perm os.FileMode) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, perm); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func generateRandomSecret() string {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		panic(fmt.Sprintf("failed to generate random secret: %v", err))
	}
	return hex.EncodeToString(b)
}
